"""SSHClient — SSH tunnel + remote RAMIC daemon deployment.

Manages the SSH port-forward tunnel and remote file deployment independently
from the SKILL execution client (VirtuosoClient). VirtuosoClient only needs a
localhost:port TCP endpoint; SSHClient makes that endpoint available.
"""

from __future__ import annotations

import importlib.resources
import json
import logging
import os
import re
import shutil
import socket
import sys
import time
from pathlib import Path
from typing import Any

from virtuoso_bridge.env import load_vb_env, resolve_env_path
from virtuoso_bridge.profile import resolve_profile
from virtuoso_bridge.runtime_paths import legacy_cache_state_file, state_dir
from virtuoso_bridge.transport.remote_paths import (
    default_virtuoso_bridge_dir,
    resolve_client_id,
    resolve_remote_username,
)
from virtuoso_bridge.transport.ssh import SSHRunner, CommandResult

logger = logging.getLogger(__name__)

_TUNNEL_STARTUP_SETTLE_SECONDS = 1.0
def _is_localhost(host: str | None) -> bool:
    """Return True if *host* refers to the local machine."""
    if not host:
        return False
    return host.strip().lower() in ("localhost", "127.0.0.1", "::1")


def _state_file(profile: str | None = None) -> Path:
    name = f"state_{profile}.json" if profile else "state.json"
    return state_dir() / name


def _state_file_candidates(profile: str | None = None) -> list[Path]:
    primary = _state_file(profile)
    legacy = legacy_cache_state_file(profile)
    return [primary] if primary == legacy else [primary, legacy]

# ---------------------------------------------------------------------------
# Resource helpers (moved from bridge.py)
# ---------------------------------------------------------------------------

def _find_ramic_bridge_il() -> Path:
    try:
        resources = importlib.resources.files("virtuoso_bridge.virtuoso.basic.resources")
        il_ref = resources / "ramic_bridge.il"
        with importlib.resources.as_file(il_ref) as il_path:
            if il_path.is_file():
                return il_path
    except (ModuleNotFoundError, FileNotFoundError, TypeError):
        pass
    raise FileNotFoundError(
        "Cannot locate ramic_bridge.il in virtuoso_bridge.virtuoso.basic.resources."
    )


def _find_ramic_bridge_daemon(python_major: int) -> Path:
    filename = "ramic_bridge_daemon_3.py" if python_major >= 3 else "ramic_bridge_daemon_27.py"
    try:
        resources = importlib.resources.files("virtuoso_bridge.virtuoso.basic.resources")
        daemon_ref = resources / filename
        with importlib.resources.as_file(daemon_ref) as daemon_path:
            if daemon_path.is_file():
                return daemon_path
    except (ModuleNotFoundError, FileNotFoundError, TypeError):
        pass
    raise FileNotFoundError(f"Cannot locate {filename} in virtuoso_bridge.virtuoso.basic.resources.")



def _generate_virtuoso_setup_il(daemon_path: str, il_path: str, python_cmd: str = "python", port: int = 65432) -> str:
    return (
        "; Virtuoso CIW Setup Script - RAMIC Bridge\n"
        "; Auto-generated by virtuoso-bridge\n"
        f'; Execute in CIW: load("{il_path.replace(chr(0x5c), "/")}")\n'
        "\n"
        "; Set environment variables\n"
        f'setShellEnvVar("RB_DAEMON_PATH" "{daemon_path}")\n'
        f'setShellEnvVar("RB_PYTHON_PATH" "{python_cmd}")\n'
        f'setShellEnvVar("RB_PORT" "{port}")\n'
        "\n"
        "; Load RAMIC Bridge IL script\n"
        f'load("{il_path}")\n'
        "\n"
        "; Setup complete!\n"
    )


def _update_env_file(key: str, value: str) -> bool:
    try:
        env_path = resolve_env_path()
    except FileNotFoundError:
        return False
    if env_path is not None and env_path.is_file():
        text = env_path.read_text(encoding="utf-8")
        new_text = re.sub(
            rf"^{re.escape(key)}\s*=.*$",
            f"{key}={value}",
            text,
            flags=re.MULTILINE,
        )
        if new_text != text:
            env_path.write_text(new_text, encoding="utf-8")
            logger.info("Updated %s=%s in %s", key, value, env_path)
            return True
        return False
    return False


def _profiled_bridge_leaf(profile: str | None) -> str:
    """Remote bridge directory leaf for a connection profile."""
    if not profile:
        return "virtuoso_bridge"
    safe = re.sub(r"[^a-zA-Z0-9._-]", "_", profile.strip())[:64]
    return f"virtuoso_bridge_{safe or 'profile'}"


def _profiled_env_key(base: str, profile: str | None) -> str:
    return f"{base}_{profile}" if profile else base


# ---------------------------------------------------------------------------
# SSHClient
# ---------------------------------------------------------------------------

class SSHClient:
    """Manages SSH tunnel and remote RAMIC daemon deployment.

    Provides a localhost:port TCP endpoint that tunnels to the remote daemon.
    Completely independent of SKILL execution logic.
    """

    def __init__(
        self,
        remote_host: str,
        remote_user: str | None = None,
        port: int = 65432,
        local_port: int | None = None,
        jump_host: str | None = None,
        jump_user: str | None = None,
        timeout: int = 30,
        keep_remote_files: bool = False,
        profile: str | None = None,
    ) -> None:
        self._remote_host = remote_host
        self._remote_user = remote_user
        self._port = port  # remote daemon port
        self._local_port = local_port if local_port is not None else port
        self._jump_host = jump_host
        self._jump_user = jump_user
        self._timeout = timeout
        self._keep_remote_files = keep_remote_files
        self._profile = profile

        if _is_localhost(remote_host):
            self._ssh_runner = None
        else:
            self._ssh_runner = SSHRunner(
                host=remote_host,
                user=remote_user,
                jump_host=jump_host,
                jump_user=jump_user,
                persistent_shell=True,
                verbose=True,
            )

        self._remote_setup_done = False
        self._remote_work_dir: str | None = None
        self._remote_virtuoso_setup_path: str | None = None

    # -- factory methods ----------------------------------------------------

    @classmethod
    def from_env(cls, *, keep_remote_files: bool = False, profile: str | None = None) -> "SSHClient":
        """Create from VB_* environment variables.

        If *profile* is given (e.g. ``"gpu1"``), reads ``VB_REMOTE_HOST_gpu1``
        etc.  Otherwise resolves a profile binding before falling back to the
        default unsuffixed variables.
        """
        profile = resolve_profile(profile)
        load_vb_env()

        suffix = f"_{profile}" if profile else ""

        remote_host = os.getenv(f"VB_REMOTE_HOST{suffix}", "").strip()
        if not remote_host:
            var = f"VB_REMOTE_HOST{suffix}"
            raise RuntimeError(f"{var} must be set")

        remote_user = os.getenv(f"VB_REMOTE_USER{suffix}", "").strip() or None
        jump_host = os.getenv(f"VB_JUMP_HOST{suffix}", "").strip() or None
        jump_user = os.getenv(f"VB_JUMP_USER{suffix}", "").strip() or None

        # Port
        from virtuoso_bridge.virtuoso.basic.bridge import _default_remote_port
        try:
            port = int(os.getenv(f"VB_REMOTE_PORT{suffix}", "").strip() or _default_remote_port(remote_user))
        except (ValueError, TypeError):
            port = _default_remote_port(remote_user)

        # Local port (defaults to remote port if not set)
        local_port_str = os.getenv(f"VB_LOCAL_PORT{suffix}", "").strip()
        local_port: int | None = None
        if local_port_str:
            try:
                local_port = int(local_port_str)
            except (ValueError, TypeError):
                pass

        return cls(
            remote_host=remote_host,
            remote_user=remote_user,
            port=port,
            local_port=local_port,
            jump_host=jump_host,
            jump_user=jump_user,
            keep_remote_files=keep_remote_files,
            profile=profile,
        )

    # -- properties ---------------------------------------------------------

    @property
    def port(self) -> int:
        """Port that VirtuosoClient should connect to.

        In local mode there is no SSH tunnel, so the client connects
        directly to the daemon port.  In remote mode the client connects
        to the local end of the SSH tunnel.
        """
        if _is_localhost(self._remote_host):
            return self._port
        return self._local_port

    @property
    def remote_host(self) -> str:
        return self._remote_host

    @property
    def ssh_runner(self) -> SSHRunner | None:
        return self._ssh_runner

    def _require_runner(self) -> SSHRunner:
        runner = self._ssh_runner
        if runner is None:
            raise RuntimeError("SSH runner is unavailable in local mode")
        return runner

    @property
    def remote_work_dir(self) -> str | None:
        return self._remote_work_dir

    @property
    def setup_path(self) -> str | None:
        return self._remote_virtuoso_setup_path

    @property
    def is_tunnel_alive(self) -> bool:
        if self._ssh_runner is None:
            return False
        return self._ssh_runner.is_tunnel_alive

    # -- remote deployment --------------------------------------------------

    def _detect_remote_python(self) -> tuple[str, int, int]:
        # Try Cadence-bundled Python 3.9+ first (IC23.1+), then system python3,
        # then generic python, then python2.7.
        detect_cmd = (
            '(test -x "$CDSHOME/tools.lnx86/python/64bit/bin/python3" && '
            '$CDSHOME/tools.lnx86/python/64bit/bin/python3 --version 2>&1 && '
            'echo "CMD:$CDSHOME/tools.lnx86/python/64bit/bin/python3") || '
            '(python3 --version 2>&1 && echo "CMD:python3") || '
            '(python --version 2>&1 && echo "CMD:python") || '
            '(python2.7 --version 2>&1 && echo "CMD:python2.7") || '
            'echo "CMD:NONE"'
        )
        runner = self._require_runner()
        result = runner.run_command(detect_cmd)
        output = result.stdout.strip()
        stderr = result.stderr.strip()
        logger.info("Remote Python detection output: %s", output)

        python_cmd = None
        python_major = None
        python_minor = 0
        for line in output.splitlines():
            line = line.strip()
            if line.startswith("CMD:"):
                cmd = line[4:]
                if cmd != "NONE":
                    python_cmd = cmd
            elif line.startswith("Python "):
                try:
                    parts = line.split()[1].split(".")
                    python_major = int(parts[0])
                    python_minor = int(parts[1]) if len(parts) > 1 else 0
                except (IndexError, ValueError):
                    pass

        if python_cmd is None or python_major is None:
            details = f"Detection output: {output!r}"
            if stderr:
                details += f". SSH stderr: {stderr!r}"
            if result.returncode != 0:
                details += f". SSH return code: {result.returncode}"
            raise RuntimeError(
                f"No Python interpreter found on {self._remote_host}. "
                f"{details}"
            )
        logger.info("Detected remote Python: %s (version %d.%d)", python_cmd, python_major, python_minor)
        return python_cmd, python_major, python_minor

    def ensure_remote_setup(self) -> None:
        """Upload daemon files and generate virtuoso_setup.il on the remote host."""
        if self._remote_setup_done:
            return

        runner = self._require_runner()
        python_cmd, python_major, python_minor = self._detect_remote_python()
        daemon_local = _find_ramic_bridge_daemon(
            3 if python_major >= 3 else 2
        )
        il_local = _find_ramic_bridge_il()
        daemon_filename = daemon_local.name

        remote_username = resolve_remote_username(
            configured_user=self._remote_user,
            runner=runner,
        )
        self._remote_work_dir = default_virtuoso_bridge_dir(
            remote_username,
            _profiled_bridge_leaf(self._profile),
            resolve_client_id(self._profile),
        )

        remote_daemon = f"{self._remote_work_dir}/{daemon_filename}"
        remote_il = f"{self._remote_work_dir}/ramic_bridge.il"
        remote_setup = f"{self._remote_work_dir}/virtuoso_setup.il"

        logger.info("Creating remote directory: %s", self._remote_work_dir)
        mkdir_result = runner.run_command(
            f"mkdir -p {self._remote_work_dir} && chmod 755 {self._remote_work_dir}"
        )
        if mkdir_result.returncode != 0:
            raise RuntimeError(f"Failed to create remote directory: {mkdir_result.stderr.strip()}")

        logger.info("Uploading daemon script (%s) to %s", daemon_filename, remote_daemon)
        daemon_content = daemon_local.read_text(encoding="utf-8")
        up = runner.upload_text(daemon_content, remote_daemon)
        if up.returncode != 0:
            raise RuntimeError(f"Failed to upload daemon: {up.stderr.strip()}")

        logger.info("Uploading IL script to %s", remote_il)
        il_content = il_local.read_text(encoding="utf-8")
        up = runner.upload_text(il_content, remote_il)
        if up.returncode != 0:
            raise RuntimeError(f"Failed to upload IL script: {up.stderr.strip()}")

        setup_content = _generate_virtuoso_setup_il(remote_daemon, remote_il, python_cmd, port=self._port)
        logger.info("Uploading setup script to %s", remote_setup)
        up = runner.upload_text(setup_content, remote_setup)
        if up.returncode != 0:
            raise RuntimeError(f"Failed to upload setup script: {up.stderr.strip()}")

        self._remote_setup_done = True
        self._remote_virtuoso_setup_path = remote_setup
        logger.info("Remote setup complete; setup script at %s (using %s)", remote_setup, python_cmd)

    def ensure_local_setup(self) -> None:
        """Generate virtuoso_setup.il locally (no SSH needed)."""
        if self._remote_setup_done:
            return

        python_cmd = sys.executable
        python_major = sys.version_info[0]

        daemon_local = _find_ramic_bridge_daemon(python_major)
        il_local = _find_ramic_bridge_il()

        # Determine local work directory
        if self._profile:
            work_dir = state_dir() / f"local_{self._profile}"
        else:
            work_dir = state_dir() / "local"
        work_dir.mkdir(parents=True, exist_ok=True)

        # Copy daemon and IL files into the work directory
        local_daemon = work_dir / daemon_local.name
        local_il = work_dir / "ramic_bridge.il"
        local_setup = work_dir / "virtuoso_setup.il"

        shutil.copy2(daemon_local, local_daemon)

        il_content = il_local.read_text(encoding="utf-8")
        local_il.write_text(il_content, encoding="utf-8")

        setup_content = _generate_virtuoso_setup_il(
            str(local_daemon), str(local_il), python_cmd, port=self._port
        )
        local_setup.write_text(setup_content, encoding="utf-8")

        self._remote_setup_done = True
        self._remote_virtuoso_setup_path = str(local_setup)
        self._remote_work_dir = str(work_dir)
        logger.info(
            "Local setup complete; setup script at %s (using %s)",
            local_setup, python_cmd,
        )

    # -- SSH tunnel (delegated to SSHRunner) ----------------------------------

    def ensure_tunnel(self) -> None:
        """Ensure SSH tunnel is running, auto-retry on port conflict."""
        if _is_localhost(self._remote_host):
            return
        runner = self._require_runner()
        if runner.is_tunnel_alive:
            return
        if SSHRunner.can_reach_port(self._local_port):
            # Port reachable (external tunnel) — load PID from state if available
            state = self.read_state(self._profile)
            if state and state.get("tunnel_pid"):
                runner.tunnel_pid = state["tunnel_pid"]
            return

        max_attempts = 10
        local_port = self._local_port
        for attempt in range(max_attempts):
            settle = _TUNNEL_STARTUP_SETTLE_SECONDS
            if self._jump_host:
                settle = max(settle, 3.0)
            proc = runner.start_port_forward(local_port, settle=settle, remote_port=self._port)
            if proc is None:
                # Reusing existing tunnel
                self._local_port = local_port
                return
            if proc.poll() is None:
                # Tunnel running
                if local_port != self._local_port:
                    logger.info("Local port %d was busy, using port %d", self._local_port, local_port)
                    print(f"[port] {self._local_port} busy, auto-switched to {local_port}", flush=True)
                    self._local_port = local_port
                    _update_env_file(_profiled_env_key("VB_LOCAL_PORT", self._profile), str(local_port))
                logger.info(
                    "SSH tunnel established (PID %d): localhost:%d -> %s:localhost:%d",
                    proc.pid, local_port, self._remote_host, self._port,
                )
                return
            # Failed
            stderr = proc.stderr
            err_msg = stderr.read().decode("utf-8", errors="ignore") if stderr else ""
            if "address already in use" in err_msg.lower() or "cannot listen" in err_msg.lower():
                logger.info("Local port %d in use, trying %d", local_port, local_port + 1)
                local_port += 1
                continue
            raise RuntimeError(f"SSH tunnel failed: {err_msg.strip()}")

        raise RuntimeError(f"No free local port found after {max_attempts} attempts ({self._local_port}-{local_port - 1})")

    # -- high-level lifecycle -----------------------------------------------

    def warm(self, timeout: int = 15) -> None:
        """Full startup: remote setup + persistent shell + tunnel."""
        if _is_localhost(self._remote_host):
            self.ensure_local_setup()
            self.save_state()
            return
        try:
            self.ensure_remote_setup()
            runner = self._require_runner()
            if runner.persistent_shell_enabled:
                runner.ensure_persistent_shell(timeout=timeout)
            self.ensure_tunnel()
            self.save_state()
        except Exception:
            try:
                self.close()
            except Exception:
                pass
            raise

    def stop(self) -> None:
        """Kill the tunnel and clean up."""
        if _is_localhost(self._remote_host):
            # Local mode: no tunnel or SSH to tear down — just clear state
            sf = _state_file(self._profile)
            if sf.exists():
                sf.unlink(missing_ok=True)
            return

        runner = self._require_runner()
        # Try state file PID first (may be from a previous session)
        if not runner.is_tunnel_alive:
            state = self.read_state(self._profile)
            if state:
                pid = state.get("tunnel_pid")
                if pid:
                    runner.tunnel_pid = pid

        runner.stop_port_forward()

        if not self._keep_remote_files and self._remote_setup_done and self._remote_work_dir:
            try:
                runner.run_command(f"rm -rf {self._remote_work_dir}")
            except Exception:
                logger.warning("Failed to clean up remote files at %s", self._remote_work_dir)

        try:
            runner.close()
        except Exception:
            pass

        # Clear state
        sf = _state_file(self._profile)
        if sf.exists():
            sf.unlink(missing_ok=True)

    def close(self) -> None:
        """Close SSH runner without killing the tunnel (it survives for other scripts)."""
        if self._ssh_runner is None:
            return
        try:
            self._ssh_runner.close()
        except Exception:
            pass

    # -- state file ---------------------------------------------------------

    def save_state(self) -> None:
        """Save tunnel state so other processes can find the port."""
        state_dir().mkdir(parents=True, exist_ok=True)
        is_local = _is_localhost(self._remote_host)
        tunnel_pid = None
        if not is_local:
            tunnel_pid = self._require_runner().tunnel_pid
        state = {
            "mode": "local" if is_local else "remote",
            "port": self._port if is_local else self._local_port,
            "tunnel_pid": tunnel_pid,
            "remote_host": self._remote_host,
            "setup_path": self._remote_virtuoso_setup_path,
            "profile": self._profile,
            "started_at": time.time(),
        }
        _state_file(self._profile).write_text(json.dumps(state, indent=2), encoding="utf-8")

    @staticmethod
    def read_state(profile: str | None = None) -> dict[str, Any] | None:
        """Read saved tunnel state."""
        for sf in _state_file_candidates(profile):
            if not sf.is_file():
                continue
            try:
                return json.loads(sf.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
        return None

    @classmethod
    def is_running(cls, profile: str | None = None) -> bool:
        """Check if a tunnel is running (port reachable or process alive).

        For local mode, the state file existing is sufficient — the daemon
        may not be loaded in CIW yet, so we skip port checks.
        """
        state = cls.read_state(profile)
        if not state:
            return False
        if state.get("mode") == "local":
            return True
        port = state.get("port")
        pid = state.get("tunnel_pid")
        # Primary check: is the port reachable? (works on all platforms)
        if port:
            try:
                s = socket.create_connection(("127.0.0.1", port), timeout=1)
                s.close()
                return True
            except (ConnectionRefusedError, OSError):
                pass
        # Fallback: is the process alive? (os.kill(pid, 0) on Unix)
        if pid:
            try:
                os.kill(pid, 0)
                return True
            except (OSError, PermissionError):
                pass
        return False

    # -- file transfer (delegated to SSHRunner) -----------------------------

    def upload_file(self, local_path: Path, remote_path: str, timeout: int | None = None) -> CommandResult:
        runner = self._require_runner()
        return runner.upload(local_path, remote_path, timeout=timeout or self._timeout)

    def download_file(self, remote_path: str, local_path: Path, timeout: int | None = None, recursive: bool = False) -> CommandResult:
        runner = self._require_runner()
        return runner.download(remote_path, local_path, recursive=recursive, timeout=timeout or self._timeout)

    def upload_text(self, text: str, remote_path: str, timeout: int | None = None) -> CommandResult:
        runner = self._require_runner()
        return runner.upload_text(text, remote_path, timeout=timeout or self._timeout)

    def run_command(self, cmd: str, timeout: int | None = None) -> CommandResult:
        runner = self._require_runner()
        return runner.run_command(cmd, timeout=timeout or self._timeout)
